name: publish pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: build websites
        run: |
          START_DIR=$(pwd)
          cd slides/draft && bun install && bun run build
          cd ../genaiparis2025 && bun install && bun run build
          cd ../../samples/translator_api && bun install && bun run build
          cd ../../samples/writer-api-demo && bun install && bun run build
          cd ../../samples/rewriter-api-demo && bun install && bun run build
          cd ../../samples/language-detector-demo && bun install && bun run build
          cd ../../samples/summarizer-demo && bun install && bun run build
          cd ../../samples/prompt-demo && bun install && bun run build
          cd $START_DIR
          cd samples/opencvjs/opencvjs-demo && bun install && bun run build
          cd $START_DIR
          echo "Building transformersjs-demos"
          cd samples/transformersjs/transformersjs-demos && bun install && bun run build
          echo "Building transformersjs-audio-chat"
          cd $START_DIR
          cd samples/transformersjs/transformersjs-audio-chat && bun install && bun run build
          echo "Build complete"
      - name: Copy static files
        run: |
          mv slides/draft/dist public/slides-draft
          mv slides/genaiparis2025/dist public/slides-genaiparis2025
          mv samples/translator_api/dist public/translator-api-demo
          mv samples/writer-api-demo/dist public/writer-api-demo
          mv samples/rewriter-api-demo/dist public/rewriter-api-demo
          mv samples/language-detector-demo/dist public/language-detector-demo
          mv samples/summarizer-demo/dist public/summarizer-demo
          mv samples/prompt-demo/dist public/prompt-demo
          mv samples/opencvjs/opencvjs-demo/dist public/opencvjs-demo
          mv samples/transformersjs/transformersjs-demos/dist public/transformersjs-demos
          mv samples/transformersjs/transformersjs-audio-chat/dist public/transformersjs-audio-chat
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
